defaults: &defaults
  mailchimp:
    list_id: '0dd4d49cf3'
    api_key: '27151efa6accb27bdaab7a18e1cdecb2-us6'
    email_format: 'html'
    email_double_optin: false # true will require user to confirm their email address
  app:
    signup_success_notice: "Thanks for signing up! We'll send you more information soon."
    name: 'Kinsai'
    company: 'Kinsai by Jason Doo'
    company_url: 'http://kinsaiboston.com'
    twitter_user: ''
    facebook_url: ''
    google_analytics_code: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
