defaults: &defaults
  mailchimp:
    list_id: 'b5ae30b54c'
    api_key: '9d117bbb106cfd7870552785f443cc38-us1'
    email_format: 'html'
    email_double_optin: false # true will require user to confirm their email address
  app:
    signup_success_notice: "Thanks for signing up! We'll send you more information soon."
    name: 'Kinsai'
    company: 'Kinsai by Jason Doo'
    company_url: 'http://kinsaiboston.com'
    twitter_user: ''
    facebook_url: ''
    google_analytics_code: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
